package view;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Forgot_password_page extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Forgot_password_page.class.getName());

    /**
     * Creates new form Forgot_password_page
     */
    public Forgot_password_page() {
        initComponents();
        setSize(1280, 800);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        ResetLabel = new javax.swing.JLabel();
        EnterLabel = new javax.swing.JLabel();
        RegisterLabel = new javax.swing.JLabel();
        EmailTextField = new java.awt.TextField();
        ResendOTP = new javax.swing.JToggleButton();
        DidntReceieveLabel = new javax.swing.JLabel();
        BackToLoginButton = new javax.swing.JButton();
        SendOTp = new javax.swing.JButton();
        Icon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        MS_title = new javax.swing.JLabel();
        Feature1 = new javax.swing.JLabel();
        Feature2 = new javax.swing.JLabel();
        Feature3 = new javax.swing.JLabel();
        Feature4 = new javax.swing.JLabel();
        MSIcon = new javax.swing.JLabel();
        DontWorrylabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        NotifIcon = new javax.swing.JLabel();
        SearchIcon = new javax.swing.JLabel();
        RocketIcon = new javax.swing.JLabel();
        CardIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel3.setBackground(new java.awt.Color(242, 242, 242));
        panel3.setForeground(java.awt.Color.black);

        ResetLabel.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        ResetLabel.setText("RESET PASSWORD");

        EnterLabel.setForeground(java.awt.Color.gray);
        EnterLabel.setText("Enter your registered email to recieve an OTP.");

        RegisterLabel.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        RegisterLabel.setForeground(new java.awt.Color(122, 134, 154));
        RegisterLabel.setText("REGISTERED EMAIL");

        EmailTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        EmailTextField.setForeground(java.awt.Color.gray);
        EmailTextField.addActionListener(this::EmailTextFieldActionPerformed);

        ResendOTP.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        ResendOTP.setForeground(new java.awt.Color(0, 135, 90));
        ResendOTP.setText("Resend OTP");
        ResendOTP.addActionListener(this::ResendOTPActionPerformed);

        DidntReceieveLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        DidntReceieveLabel.setForeground(new java.awt.Color(122, 134, 154));
        DidntReceieveLabel.setText("Didn't receive the OTP?");

        BackToLoginButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        BackToLoginButton.setForeground(new java.awt.Color(30, 58, 104));
        BackToLoginButton.setText("<- Back to Login");

        SendOTp.setBackground(new java.awt.Color(30, 58, 104));
        SendOTp.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        SendOTp.setForeground(java.awt.Color.white);
        SendOTp.setText("SEND OTP ->");
        SendOTp.addActionListener(this::SendOTpActionPerformed);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(EnterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(BackToLoginButton)
                        .addGap(244, 244, 244))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(ResetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterLabel)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(Icon))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SendOTp, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(DidntReceieveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ResendOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EnterLabel)
                .addGap(49, 49, 49)
                .addComponent(RegisterLabel)
                .addGap(20, 20, 20)
                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(SendOTp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResendOTP)
                    .addComponent(DidntReceieveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(BackToLoginButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(990, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(697, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(30, 58, 104));

        MS_title.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        MS_title.setForeground(java.awt.Color.black);
        MS_title.setText("Library MS");

        Feature1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Feature1.setForeground(java.awt.Color.black);
        Feature1.setText("Many smart features ");

        Feature2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Feature2.setForeground(java.awt.Color.black);
        Feature2.setText("Real-time notifications");

        Feature3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Feature3.setForeground(java.awt.Color.black);
        Feature3.setText("Online fine payments");

        Feature4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Feature4.setForeground(java.awt.Color.black);
        Feature4.setText("Personalized recommendations");

        DontWorrylabel.setForeground(new java.awt.Color(249, 250, 251));
        DontWorrylabel.setText("Don't worry - we'll help you get back in securely");

        jLabel14.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(122, 134, 154));
        jLabel14.setText("© 2026 Softwarica College of IT & E-commerce · Coventry University");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(MSIcon)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NotifIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SearchIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RocketIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CardIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Feature1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Feature2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Feature3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Feature4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DontWorrylabel)
                            .addComponent(MS_title)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(MSIcon)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MS_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DontWorrylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(Feature1))
                    .addComponent(SearchIcon))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Feature2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(NotifIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Feature3)
                    .addComponent(CardIcon))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Feature4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RocketIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(280, 280, 280)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void ResendOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResendOTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResendOTPActionPerformed

    private void SendOTpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendOTpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SendOTpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Forgot_password_page().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BackToLoginButton;
    public javax.swing.JLabel CardIcon;
    public javax.swing.JLabel DidntReceieveLabel;
    public javax.swing.JLabel DontWorrylabel;
    public java.awt.TextField EmailTextField;
    public javax.swing.JLabel EnterLabel;
    public javax.swing.JLabel Feature1;
    public javax.swing.JLabel Feature2;
    public javax.swing.JLabel Feature3;
    public javax.swing.JLabel Feature4;
    public javax.swing.JLabel Icon;
    public javax.swing.JLabel MSIcon;
    public javax.swing.JLabel MS_title;
    public javax.swing.JLabel NotifIcon;
    public javax.swing.JLabel RegisterLabel;
    public javax.swing.JToggleButton ResendOTP;
    public javax.swing.JLabel ResetLabel;
    public javax.swing.JLabel RocketIcon;
    public javax.swing.JLabel SearchIcon;
    public javax.swing.JButton SendOTp;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JPanel jPanel1;
    public java.awt.Panel panel1;
    public java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
