/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class LMS_Login_Page extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LMS_Login_Page.class.getName());

    /**
     * Creates new form LMS_Login_Page
     */
    public LMS_Login_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MSTitle = new javax.swing.JLabel();
        SmartFT = new javax.swing.JLabel();
        Notif = new javax.swing.JLabel();
        Fine = new javax.swing.JLabel();
        RecLabel = new javax.swing.JLabel();
        MainIcon = new javax.swing.JLabel();
        join_prompt = new javax.swing.JLabel();
        softwarica_label = new javax.swing.JLabel();
        noticon = new javax.swing.JLabel();
        searchicon = new javax.swing.JLabel();
        rocket_icon = new javax.swing.JLabel();
        crediticon = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        welcomebacklabel = new javax.swing.JLabel();
        prompt = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        EmailTextField = new java.awt.TextField();
        PasswordTextField = new java.awt.TextField();
        checkbox1 = new java.awt.Checkbox();
        Forgotpasswordbutton = new javax.swing.JToggleButton();
        Signinbutton = new javax.swing.JButton();
        or = new javax.swing.JLabel();
        ContinueWithGoogle = new javax.swing.JButton();
        Newprompt = new javax.swing.JLabel();
        CreateAnAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Background");

        jPanel1.setBackground(new java.awt.Color(30, 58, 104));

        MSTitle.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        MSTitle.setForeground(java.awt.Color.white);
        MSTitle.setText("Library MS");

        SmartFT.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        SmartFT.setForeground(java.awt.Color.white);
        SmartFT.setText("Many smart features ");

        Notif.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Notif.setForeground(java.awt.Color.white);
        Notif.setText("Real-time notifications");

        Fine.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        Fine.setForeground(java.awt.Color.white);
        Fine.setText("Online fine payments");

        RecLabel.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        RecLabel.setForeground(java.awt.Color.white);
        RecLabel.setText("Personalized recommendations");

        join_prompt.setForeground(new java.awt.Color(249, 250, 251));
        join_prompt.setText("Join our Library management system with modern features!");

        softwarica_label.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        softwarica_label.setForeground(new java.awt.Color(122, 134, 154));
        softwarica_label.setText("© 2026 Softwarica College of IT & E-commerce · Coventry University");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(MainIcon)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noticon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchicon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rocket_icon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(crediticon, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SmartFT, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MSTitle)
                    .addComponent(Notif, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fine, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RecLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(join_prompt))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(softwarica_label, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(MainIcon)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MSTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(join_prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(SmartFT))
                    .addComponent(searchicon))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Notif))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(noticon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Fine)
                    .addComponent(crediticon))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RecLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rocket_icon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(270, 270, 270)
                .addComponent(softwarica_label)
                .addContainerGap(661, Short.MAX_VALUE))
        );

        panel3.setBackground(new java.awt.Color(242, 242, 242));
        panel3.setForeground(java.awt.Color.white);

        welcomebacklabel.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        welcomebacklabel.setText("Welcome back!!");

        prompt.setForeground(java.awt.Color.gray);
        prompt.setText("Sign into your library account");

        Email.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(122, 134, 154));
        Email.setText("EMAIL ADDRESS ");

        Password.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(122, 134, 154));
        Password.setText("PASSWORD");

        EmailTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        EmailTextField.setForeground(java.awt.Color.gray);
        EmailTextField.addActionListener(this::EmailTextFieldActionPerformed);

        PasswordTextField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PasswordTextField.setForeground(new java.awt.Color(224, 228, 236));
        PasswordTextField.addActionListener(this::PasswordTextFieldActionPerformed);

        checkbox1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        checkbox1.setForeground(new java.awt.Color(122, 134, 154));
        checkbox1.setLabel("Remember me");

        Forgotpasswordbutton.setBackground(new java.awt.Color(242, 242, 242));
        Forgotpasswordbutton.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        Forgotpasswordbutton.setForeground(new java.awt.Color(0, 135, 90));
        Forgotpasswordbutton.setText("Forgot password?");
        Forgotpasswordbutton.setBorder(null);

        Signinbutton.setBackground(new java.awt.Color(30, 58, 104));
        Signinbutton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        Signinbutton.setForeground(java.awt.Color.white);
        Signinbutton.setText("SIGN IN ->");

        or.setForeground(java.awt.Color.lightGray);
        or.setText("OR");

        ContinueWithGoogle.setBackground(new java.awt.Color(249, 250, 251));
        ContinueWithGoogle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        ContinueWithGoogle.setForeground(java.awt.Color.lightGray);
        ContinueWithGoogle.setText("Continue with Google");
        ContinueWithGoogle.addActionListener(this::ContinueWithGoogleActionPerformed);

        Newprompt.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        Newprompt.setForeground(new java.awt.Color(122, 134, 154));
        Newprompt.setText("New to Library MS?");

        CreateAnAccount.setBackground(new java.awt.Color(242, 242, 242));
        CreateAnAccount.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        CreateAnAccount.setForeground(new java.awt.Color(0, 135, 90));
        CreateAnAccount.setText("Create an account");
        CreateAnAccount.setBorder(null);
        CreateAnAccount.addActionListener(this::CreateAnAccountActionPerformed);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(or, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(Signinbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(ContinueWithGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))))
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email)
                            .addComponent(Password)
                            .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Forgotpasswordbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(welcomebacklabel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(Newprompt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreateAnAccount)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(welcomebacklabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prompt)
                .addGap(30, 30, 30)
                .addComponent(Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(Password)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(Forgotpasswordbutton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(Signinbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(or)
                .addGap(23, 23, 23)
                .addComponent(ContinueWithGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Newprompt)
                    .addComponent(CreateAnAccount))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(540, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void ContinueWithGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueWithGoogleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContinueWithGoogleActionPerformed

    private void CreateAnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAnAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateAnAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LMS_Login_Page().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContinueWithGoogle;
    private javax.swing.JButton CreateAnAccount;
    private javax.swing.JLabel Email;
    private java.awt.TextField EmailTextField;
    private javax.swing.JLabel Fine;
    private javax.swing.JToggleButton Forgotpasswordbutton;
    private javax.swing.JLabel MSTitle;
    private javax.swing.JLabel MainIcon;
    private javax.swing.JLabel Newprompt;
    private javax.swing.JLabel Notif;
    private javax.swing.JLabel Password;
    private java.awt.TextField PasswordTextField;
    private javax.swing.JLabel RecLabel;
    private javax.swing.JButton Signinbutton;
    private javax.swing.JLabel SmartFT;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JLabel crediticon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel join_prompt;
    private javax.swing.JLabel noticon;
    private javax.swing.JLabel or;
    private java.awt.Panel panel1;
    private java.awt.Panel panel3;
    private javax.swing.JLabel prompt;
    private javax.swing.JLabel rocket_icon;
    private javax.swing.JLabel searchicon;
    private javax.swing.JLabel softwarica_label;
    private javax.swing.JLabel welcomebacklabel;
    // End of variables declaration//GEN-END:variables
}
