package view;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
public class MyBorrowingsUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyBorrowingsUI.class.getName());

    /**
     * Creates new form MyBorrowingsUI
     */
    public MyBorrowingsUI() {
        initComponents();
        setSize(1280, 800);
        setLocationRelativeTo(null);
        populateFines();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DashboardButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BookSearchButton = new javax.swing.JButton();
        BorrowingButton = new javax.swing.JButton();
        WishlistButton = new javax.swing.JButton();
        ReviewsButton = new javax.swing.JButton();
        FineButton = new javax.swing.JButton();
        MyAccountButton = new javax.swing.JButton();
        InventoryButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        UsersButton = new javax.swing.JButton();
        ReportsButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        SearchBar = new javax.swing.JTextField();
        NotificationsButton = new javax.swing.JButton();
        ProfileButton = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        BorrowingHistoryButton = new javax.swing.JToggleButton();
        WishlistButton2 = new javax.swing.JToggleButton();
        ReviewsButton2 = new javax.swing.JToggleButton();
        FineButton2 = new javax.swing.JToggleButton();
        EditProfileButton = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        MembershipTypeLabel = new javax.swing.JLabel();
        MembershipTypeLabel1 = new javax.swing.JLabel();
        MembershipTypeLabel2 = new javax.swing.JLabel();
        MembershipTypeLabel3 = new javax.swing.JLabel();
        MembershipTypeLabel4 = new javax.swing.JLabel();
        MembershipTypeLabel5 = new javax.swing.JLabel();
        BookName1 = new javax.swing.JLabel();
        BookName2 = new javax.swing.JLabel();
        BookName3 = new javax.swing.JLabel();
        BookName4 = new javax.swing.JLabel();
        BookName5 = new javax.swing.JLabel();
        BookName6 = new javax.swing.JLabel();
        BookName8 = new javax.swing.JLabel();
        BookName9 = new javax.swing.JLabel();
        AuthorName1 = new javax.swing.JLabel();
        AuthorName2 = new javax.swing.JLabel();
        AuthorName3 = new javax.swing.JLabel();
        AuthorName4 = new javax.swing.JLabel();
        AuthorName5 = new javax.swing.JLabel();
        AuthorName6 = new javax.swing.JLabel();
        AuthorName7 = new javax.swing.JLabel();
        AuthorName8 = new javax.swing.JLabel();
        BorrowedDate1 = new javax.swing.JLabel();
        BorrowedDate2 = new javax.swing.JLabel();
        BorrowedDate3 = new javax.swing.JLabel();
        BorrowedDate4 = new javax.swing.JLabel();
        BorrowedDate5 = new javax.swing.JLabel();
        BorrowedDate6 = new javax.swing.JLabel();
        BorrowedDate7 = new javax.swing.JLabel();
        ReturnedDate1 = new javax.swing.JLabel();
        BorrowedDate10 = new javax.swing.JLabel();
        ReturnedDate2 = new javax.swing.JLabel();
        ReturnedDate3 = new javax.swing.JLabel();
        ReturnedDate4 = new javax.swing.JLabel();
        ReturnedDate5 = new javax.swing.JLabel();
        ReturnedDate6 = new javax.swing.JLabel();
        ReturnedDate7 = new javax.swing.JLabel();
        ReturnedDate9 = new javax.swing.JLabel();
        ActiveStatus1 = new java.awt.Label();
        Fine7 = new java.awt.Label();
        ReturnedDate = new java.awt.Label();
        ActiveStatus2 = new java.awt.Label();
        ActiveStatus3 = new java.awt.Label();
        ReturnedStatus3 = new java.awt.Label();
        OverdueStatus2 = new java.awt.Label();
        OverDueLabel = new java.awt.Label();
        Fine2 = new java.awt.Label();
        ReturnedStatus2 = new java.awt.Label();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        Fine6 = new javax.swing.JLabel();
        Fine8 = new javax.swing.JLabel();
        Fine4 = new javax.swing.JLabel();
        Fine5 = new javax.swing.JLabel();
        Fine3 = new javax.swing.JLabel();
        Fine1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 58, 107));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LibraryMs");

        DashboardButton.setBackground(new java.awt.Color(27, 58, 107));
        DashboardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DashboardButton.setForeground(new java.awt.Color(255, 255, 255));
        DashboardButton.setText("Dashboard");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MEMBER");

        BookSearchButton.setBackground(new java.awt.Color(27, 58, 107));
        BookSearchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BookSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        BookSearchButton.setText(" Book Search");

        BorrowingButton.setBackground(new java.awt.Color(27, 58, 107));
        BorrowingButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BorrowingButton.setForeground(new java.awt.Color(255, 255, 255));
        BorrowingButton.setText(" My Borrowings");

        WishlistButton.setBackground(new java.awt.Color(27, 58, 107));
        WishlistButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        WishlistButton.setForeground(new java.awt.Color(255, 255, 255));
        WishlistButton.setText(" Wishlist");

        ReviewsButton.setBackground(new java.awt.Color(27, 58, 107));
        ReviewsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReviewsButton.setForeground(new java.awt.Color(255, 255, 255));
        ReviewsButton.setText(" Reviews");

        FineButton.setBackground(new java.awt.Color(27, 58, 107));
        FineButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FineButton.setForeground(new java.awt.Color(255, 255, 255));
        FineButton.setText(" Fine Payment");

        MyAccountButton.setBackground(new java.awt.Color(27, 58, 107));
        MyAccountButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MyAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        MyAccountButton.setText(" My Account");

        InventoryButton.setBackground(new java.awt.Color(27, 58, 107));
        InventoryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InventoryButton.setForeground(new java.awt.Color(255, 255, 255));
        InventoryButton.setText("Inventory");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("ADMIN");

        UsersButton.setBackground(new java.awt.Color(27, 58, 107));
        UsersButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsersButton.setForeground(new java.awt.Color(255, 255, 255));
        UsersButton.setText("Users");

        ReportsButton.setBackground(new java.awt.Color(27, 58, 107));
        ReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportsButton.setText("Reports");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Safal Bhandari");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Student Member");

        jButton11.setBackground(new java.awt.Color(0, 255, 102));
        jButton11.setText("SB");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-wishlist.png"))); // NOI18N
        jLabel19.setText("jLabel14");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-reviews.png"))); // NOI18N
        jLabel20.setText("jLabel14");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-fine-payment.png"))); // NOI18N
        jLabel24.setText("jLabel14");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-my-account.png"))); // NOI18N
        jLabel25.setText("jLabel14");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-borrowing-history.png"))); // NOI18N
        jLabel26.setText("jLabel14");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-dashboard.png"))); // NOI18N
        jLabel27.setText("jLabel14");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-book-search.png"))); // NOI18N
        jLabel28.setText("jLabel14");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-inventory.png"))); // NOI18N
        jLabel29.setText("jLabel14");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-users.png"))); // NOI18N
        jLabel30.setText("jLabel14");

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-reports.png"))); // NOI18N
        jLabel31.setText("jLabel14");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReportsButton)
                            .addComponent(UsersButton)
                            .addComponent(jLabel1)
                            .addComponent(BorrowingButton)
                            .addComponent(DashboardButton)
                            .addComponent(BookSearchButton)
                            .addComponent(WishlistButton)
                            .addComponent(FineButton)
                            .addComponent(ReviewsButton)
                            .addComponent(jLabel4)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InventoryButton)
                            .addComponent(MyAccountButton))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DashboardButton)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookSearchButton)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BorrowingButton)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WishlistButton)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReviewsButton)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FineButton)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MyAccountButton)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InventoryButton)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsersButton)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReportsButton)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addGap(51, 51, 51)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.Color.white);

        jButton12.setBackground(new java.awt.Color(27, 58, 107));
        jButton12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton12.setForeground(java.awt.Color.white);
        jButton12.setText("SB");

        jLabel2.setText("Safal Bhandari");

        jLabel3.setText("ID : LIB2004 - STUDENT");

        jLabel5.setBackground(new java.awt.Color(27, 58, 107));
        jLabel5.setForeground(new java.awt.Color(27, 58, 107));
        jLabel5.setText("Active Member ✓");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel6.setText("24");

        jLabel7.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel7.setText("3");

        jLabel8.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel8.setText("2");

        jLabel9.setForeground(new java.awt.Color(122, 134, 154));
        jLabel9.setText("Read");

        jLabel10.setForeground(new java.awt.Color(122, 134, 154));
        jLabel10.setText("Borrrowed");

        jLabel11.setForeground(new java.awt.Color(122, 134, 154));
        jLabel11.setText("Reserved");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jPanel4.setBackground(java.awt.Color.white);

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel12.setText("My Account");

        SearchBar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.pressedBackground"));
        SearchBar.setForeground(new java.awt.Color(122, 134, 154));
        SearchBar.setText("Search books, authors, ISBN....");
        SearchBar.addActionListener(this::SearchBarActionPerformed);

        NotificationsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-notification-bell.png"))); // NOI18N
        NotificationsButton.addActionListener(this::NotificationsButtonActionPerformed);

        ProfileButton.setBackground(new java.awt.Color(0, 255, 102));
        ProfileButton.setText("SB");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-book-search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addGap(261, 261, 261)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addComponent(NotificationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(NotificationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        jPanel5.setBackground(java.awt.Color.white);

        BorrowingHistoryButton.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        BorrowingHistoryButton.setText("Borrowing History");

        WishlistButton2.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        WishlistButton2.setText("Wishlist");

        ReviewsButton2.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        ReviewsButton2.setText("My Reviews");

        FineButton2.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        FineButton2.setText("Fines and Payment");

        EditProfileButton.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        EditProfileButton.setText("Edit profile");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-borrowing-history.png"))); // NOI18N
        jLabel14.setText("jLabel14");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-wishlist.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-fine-payment.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-edit-profile.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-reviews.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FineButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReviewsButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WishlistButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BorrowingHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BorrowingHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WishlistButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ReviewsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FineButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(java.awt.Color.white);

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel17.setText("Borrowing History");

        MembershipTypeLabel.setForeground(new java.awt.Color(122, 134, 154));
        MembershipTypeLabel.setText("Book");

        MembershipTypeLabel1.setForeground(new java.awt.Color(122, 134, 154));
        MembershipTypeLabel1.setText("Author");

        MembershipTypeLabel2.setForeground(new java.awt.Color(122, 134, 154));
        MembershipTypeLabel2.setText("Borrowed");

        MembershipTypeLabel3.setForeground(new java.awt.Color(122, 134, 154));
        MembershipTypeLabel3.setText("Returned");

        MembershipTypeLabel4.setForeground(new java.awt.Color(122, 134, 154));
        MembershipTypeLabel4.setText("Status ");

        MembershipTypeLabel5.setForeground(new java.awt.Color(122, 134, 154));
        MembershipTypeLabel5.setText("Fine");

        BookName1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BookName1.setText("Clean Code");

        BookName2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BookName2.setText("Design Patterns");

        BookName3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BookName3.setText("My Wife");

        BookName4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BookName4.setText("Just Me");

        BookName5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BookName5.setText("WriteMeOff");

        BookName6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BookName6.setText("Clean Code");

        BookName8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BookName8.setText("Clean Code");

        BookName9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        BookName9.setText("Clean Code");

        AuthorName1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        AuthorName1.setText("RC Martin");

        AuthorName2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        AuthorName2.setText("RC Martin");

        AuthorName3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        AuthorName3.setText("RC Martin");

        AuthorName4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        AuthorName4.setText("RC Martin");

        AuthorName5.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        AuthorName5.setText("RC Martin");

        AuthorName6.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        AuthorName6.setText("RC Martin");

        AuthorName7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        AuthorName7.setText("RC Martin");

        AuthorName8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        AuthorName8.setText("RC Martin");

        BorrowedDate1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        BorrowedDate1.setText("May 26, 2026");

        BorrowedDate2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        BorrowedDate2.setText("May 26, 2026");

        BorrowedDate3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        BorrowedDate3.setText("May 26, 2026");

        BorrowedDate4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        BorrowedDate4.setText("May 26, 2026");

        BorrowedDate5.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        BorrowedDate5.setText("May 26, 2026");

        BorrowedDate6.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        BorrowedDate6.setText("May 26, 2026");

        BorrowedDate7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        BorrowedDate7.setText("May 26, 2026");

        ReturnedDate1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        ReturnedDate1.setText("Sept 30, 2026");

        BorrowedDate10.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        BorrowedDate10.setText("May 26, 2026");

        ReturnedDate2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        ReturnedDate2.setText("null");

        ReturnedDate3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        ReturnedDate3.setText("July 2, 2026");

        ReturnedDate4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        ReturnedDate4.setText("null");

        ReturnedDate5.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        ReturnedDate5.setText("May 30, 2026");

        ReturnedDate6.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        ReturnedDate6.setText("May 30, 2026");

        ReturnedDate7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        ReturnedDate7.setText("June 22, 2026");

        ReturnedDate9.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        ReturnedDate9.setText("June 30, 2026");

        ActiveStatus1.setForeground(new java.awt.Color(255, 153, 51));
        ActiveStatus1.setText("Active");

        Fine7.setForeground(new java.awt.Color(255, 51, 51));
        Fine7.setText("Rs 75");

        ReturnedDate.setForeground(new java.awt.Color(0, 135, 90));
        ReturnedDate.setText("Returned");

        ActiveStatus2.setForeground(new java.awt.Color(255, 153, 51));
        ActiveStatus2.setText("Active");

        ActiveStatus3.setForeground(new java.awt.Color(255, 153, 51));
        ActiveStatus3.setText("Active");

        ReturnedStatus3.setForeground(new java.awt.Color(0, 135, 90));
        ReturnedStatus3.setText("Returned");

        OverdueStatus2.setForeground(new java.awt.Color(255, 51, 51));
        OverdueStatus2.setName("Overdue"); // NOI18N
        OverdueStatus2.setText("Overdue");

        OverDueLabel.setForeground(new java.awt.Color(255, 51, 51));
        OverDueLabel.setText("Overdue");

        Fine2.setForeground(new java.awt.Color(255, 51, 51));
        Fine2.setText("Rs 50");

        ReturnedStatus2.setForeground(new java.awt.Color(0, 135, 90));
        ReturnedStatus2.setText("Returned");

        Fine6.setForeground(new java.awt.Color(0, 135, 90));
        Fine6.setText("Rs 0");

        Fine8.setForeground(new java.awt.Color(0, 135, 90));
        Fine8.setText("Rs 0");

        Fine4.setForeground(new java.awt.Color(0, 135, 90));
        Fine4.setText("Rs 0");

        Fine5.setForeground(new java.awt.Color(0, 135, 90));
        Fine5.setText("Rs 0");

        Fine3.setForeground(new java.awt.Color(0, 135, 90));
        Fine3.setText("Rs 0");

        Fine1.setForeground(new java.awt.Color(0, 135, 90));
        Fine1.setText("Rs 0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BookName1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BookName4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BookName8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BookName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BookName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BookName5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BookName6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BookName9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AuthorName1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AuthorName2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AuthorName3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AuthorName4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AuthorName7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AuthorName8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AuthorName5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AuthorName6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(BorrowedDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(ReturnedDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(BorrowedDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(BorrowedDate5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(BorrowedDate6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(BorrowedDate10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(BorrowedDate4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(BorrowedDate7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                                        .addComponent(BorrowedDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)))
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ReturnedDate5)
                                                    .addComponent(ReturnedDate4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ReturnedDate7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ReturnedDate6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ReturnedDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ReturnedDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ReturnedDate9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(MembershipTypeLabel)
                                .addGap(182, 182, 182)
                                .addComponent(MembershipTypeLabel1)
                                .addGap(87, 87, 87)
                                .addComponent(MembershipTypeLabel2)
                                .addGap(85, 85, 85)
                                .addComponent(MembershipTypeLabel3)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MembershipTypeLabel4)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(OverDueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ActiveStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ReturnedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ActiveStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ActiveStatus3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ReturnedStatus2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OverdueStatus2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ReturnedStatus3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(MembershipTypeLabel5)
                                .addGap(13, 13, 13))
                            .addComponent(Fine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fine3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fine4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fine5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fine6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fine8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fine7, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(Fine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel17)
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MembershipTypeLabel)
                    .addComponent(MembershipTypeLabel1)
                    .addComponent(MembershipTypeLabel2)
                    .addComponent(MembershipTypeLabel3)
                    .addComponent(MembershipTypeLabel4)
                    .addComponent(MembershipTypeLabel5))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BookName1))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AuthorName1)
                                    .addComponent(BorrowedDate1))
                                .addComponent(ActiveStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Fine1))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReturnedDate1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BorrowedDate2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AuthorName4)
                        .addComponent(BookName5))
                    .addComponent(ReturnedDate2)
                    .addComponent(OverDueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AuthorName2)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BorrowedDate3)
                                .addComponent(ReturnedDate9))
                            .addComponent(BookName2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Fine3)
                                .addComponent(ReturnedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookName3)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AuthorName3)
                                .addComponent(BorrowedDate5)
                                .addComponent(ReturnedDate3))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Fine4)
                                .addComponent(ActiveStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookName4)
                            .addComponent(AuthorName7)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BorrowedDate6)
                                .addComponent(ReturnedDate6))
                            .addComponent(ActiveStatus3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookName8)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AuthorName8)
                                .addComponent(BorrowedDate10)
                                .addComponent(ReturnedDate7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookName6)
                            .addComponent(AuthorName5)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BorrowedDate4)
                                .addComponent(ReturnedDate4))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Fine5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ReturnedStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fine6))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OverdueStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fine7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookName9)
                    .addComponent(AuthorName6)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BorrowedDate7)
                        .addComponent(ReturnedDate5))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Fine8)
                        .addComponent(ReturnedStatus3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// =====================================================================
// HOW TO INTEGRATE FineCalculator INTO MyBorrowingsUI.java
// Add the method below inside the MyBorrowingsUI class body,
// then call it from your constructor or a "load data" method.
// =====================================================================

// ---------------------------------------------------------------------
// 1.  Add this import at the top of MyBorrowingsUI.java
// ---------------------------------------------------------------------
// import java.time.LocalDate;
// (java.time.* is available in Java 8+, no extra libraries needed)


// ---------------------------------------------------------------------
// 2.  Paste this method inside MyBorrowingsUI (below initComponents)
// ---------------------------------------------------------------------

/**
 * Populates the Fine labels in jPanel6 for every borrowing row.
 *
 * Call this method after your borrowing data has been loaded, e.g.:
 *   populateFines();          ← in constructor after initComponents()
 *   OR after a DB fetch call.
 *
 * Replace the sample hard coded dates/return values with data from
 * your database or data model.
 */
private void populateFines() {
    // Dummy code removed
}

// ------------------------------------------------------------------
// Helper: set text on either javax.swing.JLabel or java.awt.Label
// ------------------------------------------------------------------
private void setLabelText(Object label, String text) {
    if (label instanceof javax.swing.JLabel) {
        ((javax.swing.JLabel) label).setText(text);
    } else if (label instanceof java.awt.Label) {
        ((java.awt.Label) label).setText(text);
    }
}

// ------------------------------------------------------------------
// Helper: set foreground colour on either JLabel or AWT Label
// ------------------------------------------------------------------
private void setLabelColor(Object label, java.awt.Color color) {
    if (label instanceof javax.swing.JLabel) {
        ((javax.swing.JLabel) label).setForeground(color);
    } else if (label instanceof java.awt.Label) {
        ((java.awt.Label) label).setForeground(color);
    }
}

// ---------------------------------------------------------------------
// 3.  Call it in the constructor — add ONE line after initComponents()
// ---------------------------------------------------------------------
// public MyBorrowingsUI() {
//     initComponents();
//     populateFines();   // ← add this
// }


// =====================================================================
// QUICK USAGE EXAMPLES (standalone / unit-test style)
// =====================================================================

// Example A – active book that is overdue
// FineCalculator.FineResult r = FineCalculator.calculate("2025-05-01", null);
// System.out.println(r);
// → Borrowed: 2025-05-01 | Due: 2025-05-15 | Today: 2025-06-04 | Days overdue: 20 | Fine: Rs 200

// Example B – returned book, no overdue
// FineCalculator.FineResult r = FineCalculator.calculate("2025-05-20", "2025-05-30");
// System.out.println(r.fineDisplayText());  // → Rs 0

// Example C – custom loan period (7 days)
// FineCalculator.FineResult r = FineCalculator.calculate("2025-05-20", null, 7);
// System.out.println(r.fineDisplayText());  // → Rs 180

    private void NotificationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificationsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotificationsButtonActionPerformed

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MyBorrowingsUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Label ActiveStatus1;
    public java.awt.Label ActiveStatus2;
    public java.awt.Label ActiveStatus3;
    public javax.swing.JLabel AuthorName1;
    public javax.swing.JLabel AuthorName2;
    public javax.swing.JLabel AuthorName3;
    public javax.swing.JLabel AuthorName4;
    public javax.swing.JLabel AuthorName5;
    public javax.swing.JLabel AuthorName6;
    public javax.swing.JLabel AuthorName7;
    public javax.swing.JLabel AuthorName8;
    public javax.swing.JLabel BookName1;
    public javax.swing.JLabel BookName2;
    public javax.swing.JLabel BookName3;
    public javax.swing.JLabel BookName4;
    public javax.swing.JLabel BookName5;
    public javax.swing.JLabel BookName6;
    public javax.swing.JLabel BookName8;
    public javax.swing.JLabel BookName9;
    public javax.swing.JButton BookSearchButton;
    public javax.swing.JLabel BorrowedDate1;
    public javax.swing.JLabel BorrowedDate10;
    public javax.swing.JLabel BorrowedDate2;
    public javax.swing.JLabel BorrowedDate3;
    public javax.swing.JLabel BorrowedDate4;
    public javax.swing.JLabel BorrowedDate5;
    public javax.swing.JLabel BorrowedDate6;
    public javax.swing.JLabel BorrowedDate7;
    public javax.swing.JButton BorrowingButton;
    public javax.swing.JToggleButton BorrowingHistoryButton;
    public javax.swing.JButton DashboardButton;
    public javax.swing.JToggleButton EditProfileButton;
    public javax.swing.JLabel Fine1;
    public java.awt.Label Fine2;
    public javax.swing.JLabel Fine3;
    public javax.swing.JLabel Fine4;
    public javax.swing.JLabel Fine5;
    public javax.swing.JLabel Fine6;
    public java.awt.Label Fine7;
    public javax.swing.JLabel Fine8;
    public javax.swing.JButton FineButton;
    public javax.swing.JToggleButton FineButton2;
    public javax.swing.JButton InventoryButton;
    public javax.swing.JLabel MembershipTypeLabel;
    public javax.swing.JLabel MembershipTypeLabel1;
    public javax.swing.JLabel MembershipTypeLabel2;
    public javax.swing.JLabel MembershipTypeLabel3;
    public javax.swing.JLabel MembershipTypeLabel4;
    public javax.swing.JLabel MembershipTypeLabel5;
    public javax.swing.JButton MyAccountButton;
    public javax.swing.JButton NotificationsButton;
    public java.awt.Label OverDueLabel;
    public java.awt.Label OverdueStatus2;
    public javax.swing.JButton ProfileButton;
    public javax.swing.JButton ReportsButton;
    public java.awt.Label ReturnedDate;
    public javax.swing.JLabel ReturnedDate1;
    public javax.swing.JLabel ReturnedDate2;
    public javax.swing.JLabel ReturnedDate3;
    public javax.swing.JLabel ReturnedDate4;
    public javax.swing.JLabel ReturnedDate5;
    public javax.swing.JLabel ReturnedDate6;
    public javax.swing.JLabel ReturnedDate7;
    public javax.swing.JLabel ReturnedDate9;
    public java.awt.Label ReturnedStatus2;
    public java.awt.Label ReturnedStatus3;
    public javax.swing.JButton ReviewsButton;
    public javax.swing.JToggleButton ReviewsButton2;
    public javax.swing.JTextField SearchBar;
    public javax.swing.JButton UsersButton;
    public javax.swing.JButton WishlistButton;
    public javax.swing.JToggleButton WishlistButton2;
    public javax.swing.Box.Filler filler1;
    public javax.swing.JButton jButton11;
    public javax.swing.JButton jButton12;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel31;
    public javax.swing.JLabel jLabel32;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
