/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Signup_Page extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signup_Page.class.getName());

    /**
     * Creates new form Signup_Page
     */
    public Signup_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        CreateAccountTitle = new javax.swing.JLabel();
        FillInPrompt = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CreateAccountButton = new javax.swing.JButton();
        MembershipIDLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        PhNumberLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        MembershipIDTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        PhNumberTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        ConfirmPasswordTextField = new javax.swing.JTextField();
        TermsAndServicesBox = new javax.swing.JCheckBox();
        Ft1 = new javax.swing.JLabel();
        Ft2 = new javax.swing.JLabel();
        Ft3 = new javax.swing.JLabel();
        Ft4 = new javax.swing.JLabel();
        AlreadyLabel = new javax.swing.JLabel();
        SignInButton = new javax.swing.JToggleButton();
        MembershipTypeLabel = new javax.swing.JLabel();
        StudentMembership = new javax.swing.JToggleButton();
        FactultyMembership = new javax.swing.JToggleButton();
        PublicMembership = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        FeaturePrompt = new javax.swing.JLabel();
        NotifPrompt = new javax.swing.JLabel();
        PaymentPrompt = new javax.swing.JLabel();
        RecPrompt = new javax.swing.JLabel();
        MSIcon = new javax.swing.JLabel();
        CreatePrompt = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Notificon = new javax.swing.JLabel();
        SearchIcon = new javax.swing.JLabel();
        RocketIcon = new javax.swing.JLabel();
        CreditIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel3.setBackground(new java.awt.Color(242, 242, 242));
        panel3.setForeground(java.awt.Color.white);

        CreateAccountTitle.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        CreateAccountTitle.setText("CREATE ACCOUNT");

        FillInPrompt.setForeground(java.awt.Color.gray);
        FillInPrompt.setText("Fill in your account details to register as a library member");
        FillInPrompt.setToolTipText("");

        NameLabel.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(122, 134, 154));
        NameLabel.setText("Full Name");

        jLabel10.setForeground(java.awt.Color.lightGray);
        jLabel10.setText("OR");

        CreateAccountButton.setBackground(new java.awt.Color(30, 58, 104));
        CreateAccountButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        CreateAccountButton.setForeground(java.awt.Color.white);
        CreateAccountButton.setText("CREATE MY ACCOUNT ->");

        MembershipIDLabel.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        MembershipIDLabel.setForeground(new java.awt.Color(122, 134, 154));
        MembershipIDLabel.setText("Membership ID");

        EmailLabel.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(122, 134, 154));
        EmailLabel.setText("EMAIL ADDRESS");

        PasswordLabel.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(122, 134, 154));
        PasswordLabel.setText("PASSWORD");

        ConfirmPasswordLabel.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        ConfirmPasswordLabel.setForeground(new java.awt.Color(122, 134, 154));
        ConfirmPasswordLabel.setText("CONFIRM PASSWORD");

        PhNumberLabel.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        PhNumberLabel.setForeground(new java.awt.Color(122, 134, 154));
        PhNumberLabel.setText("PHONE NUMBER");

        PhNumberTextField.addActionListener(this::PhNumberTextFieldActionPerformed);

        TermsAndServicesBox.setText("I agree to the terms of service and privacy policy");

        Ft1.setForeground(new java.awt.Color(0, 135, 90));
        Ft1.setText("✓ Minimum 8 characters");

        Ft2.setForeground(new java.awt.Color(0, 135, 90));
        Ft2.setText("✓ One number (0-9)");

        Ft3.setForeground(new java.awt.Color(0, 135, 90));
        Ft3.setText("✓ One uppercase letter");

        Ft4.setForeground(new java.awt.Color(0, 135, 90));
        Ft4.setText("✓ One special character");

        AlreadyLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        AlreadyLabel.setForeground(new java.awt.Color(122, 134, 154));
        AlreadyLabel.setText("Already have an account? ");

        SignInButton.setFont(new java.awt.Font("SimSun-ExtG", 0, 14)); // NOI18N
        SignInButton.setForeground(new java.awt.Color(0, 135, 90));
        SignInButton.setText("Sign in");
        SignInButton.addActionListener(this::SignInButtonActionPerformed);

        MembershipTypeLabel.setForeground(new java.awt.Color(122, 134, 154));
        MembershipTypeLabel.setText("Membership type");

        StudentMembership.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        StudentMembership.setForeground(new java.awt.Color(30, 58, 104));
        StudentMembership.setText("Student");

        FactultyMembership.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        FactultyMembership.setForeground(new java.awt.Color(30, 58, 104));
        FactultyMembership.setText("Faculty");

        PublicMembership.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        PublicMembership.setForeground(new java.awt.Color(30, 58, 104));
        PublicMembership.setText("Public");
        PublicMembership.setAutoscrolls(true);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreateAccountTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FillInPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(AlreadyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SignInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailLabel)
                            .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhNumberLabel)
                            .addComponent(PhNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MembershipIDLabel)
                            .addComponent(MembershipIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(StudentMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(FactultyMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PublicMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(PasswordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConfirmPasswordLabel)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MembershipTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TermsAndServicesBox)
                            .addComponent(Ft1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ft2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(Ft3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ft4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(CreateAccountTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FillInPrompt)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(MembershipIDLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MembershipIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(PhNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(ConfirmPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ft2)
                    .addComponent(Ft1))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ft3)
                    .addComponent(Ft4))
                .addGap(25, 25, 25)
                .addComponent(TermsAndServicesBox)
                .addGap(18, 18, 18)
                .addComponent(MembershipTypeLabel)
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FactultyMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PublicMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlreadyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignInButton))
                .addGap(651, 651, 651)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1108, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(30, 58, 104));

        Title.setFont(new java.awt.Font("Mongolian Baiti", 1, 36)); // NOI18N
        Title.setForeground(java.awt.Color.white);
        Title.setText("Library MS");

        FeaturePrompt.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        FeaturePrompt.setForeground(java.awt.Color.white);
        FeaturePrompt.setText("Many smart features ");

        NotifPrompt.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        NotifPrompt.setForeground(java.awt.Color.white);
        NotifPrompt.setText("Real-time notifications");

        PaymentPrompt.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        PaymentPrompt.setForeground(java.awt.Color.white);
        PaymentPrompt.setText("Online fine payments");

        RecPrompt.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        RecPrompt.setForeground(java.awt.Color.white);
        RecPrompt.setText("Personalized recommendations");

        MSIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-libraryms.png"))); // NOI18N

        CreatePrompt.setForeground(new java.awt.Color(249, 250, 251));
        CreatePrompt.setText("Create your account and start borrowing books today!");

        jLabel14.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(122, 134, 154));
        jLabel14.setText("© 2026 Softwarica College of IT & E-commerce · Coventry University");

        Notificon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-notification-bell.png"))); // NOI18N

        SearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-book-search.png"))); // NOI18N

        RocketIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-stat-reservations.png"))); // NOI18N

        CreditIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-fine-payment.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(MSIcon)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Notificon, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SearchIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RocketIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CreditIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FeaturePrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NotifPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PaymentPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreatePrompt)
                            .addComponent(Title)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(MSIcon)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreatePrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(FeaturePrompt))
                    .addComponent(SearchIcon))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(NotifPrompt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Notificon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PaymentPrompt)
                    .addComponent(CreditIcon))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RecPrompt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RocketIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(280, 280, 280)
                .addComponent(jLabel14)
                .addContainerGap(504, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignInButtonActionPerformed

    private void PhNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhNumberTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Signup_Page().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlreadyLabel;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JTextField ConfirmPasswordTextField;
    private javax.swing.JButton CreateAccountButton;
    private javax.swing.JLabel CreateAccountTitle;
    private javax.swing.JLabel CreatePrompt;
    private javax.swing.JLabel CreditIcon;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JToggleButton FactultyMembership;
    private javax.swing.JLabel FeaturePrompt;
    private javax.swing.JLabel FillInPrompt;
    private javax.swing.JLabel Ft1;
    private javax.swing.JLabel Ft2;
    private javax.swing.JLabel Ft3;
    private javax.swing.JLabel Ft4;
    private javax.swing.JLabel MSIcon;
    private javax.swing.JLabel MembershipIDLabel;
    private javax.swing.JTextField MembershipIDTextField;
    private javax.swing.JLabel MembershipTypeLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel NotifPrompt;
    private javax.swing.JLabel Notificon;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JLabel PaymentPrompt;
    private javax.swing.JLabel PhNumberLabel;
    private javax.swing.JTextField PhNumberTextField;
    private javax.swing.JToggleButton PublicMembership;
    private javax.swing.JLabel RecPrompt;
    private javax.swing.JLabel RocketIcon;
    private javax.swing.JLabel SearchIcon;
    private javax.swing.JToggleButton SignInButton;
    private javax.swing.JToggleButton StudentMembership;
    private javax.swing.JCheckBox TermsAndServicesBox;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
