/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

<<<<<<< HEAD
=======
import model.Reservation;
import service.ReservationService;

>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
/**
 *
 * @author Srijal
 */
public class ui extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ui.class.getName());

<<<<<<< HEAD
=======
    // TODO: replace with the real logged-in member's name once login/session
    // handling exists. Hardcoded for now so reservations have someone to
    // attach to.
    private static final String CURRENT_MEMBER_NAME = "Current Member";

    private final ReservationService reservationService = ReservationService.getInstance();

>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
    /**
     * Creates new form ui
     */
    public ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        libraryMs = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        member = new javax.swing.JLabel();
        booksearch = new javax.swing.JButton();
        myborrowings = new javax.swing.JButton();
        wishlist = new javax.swing.JButton();
        reviews = new javax.swing.JButton();
        finepayment = new javax.swing.JButton();
        myaccount = new javax.swing.JButton();
        inventory = new javax.swing.JButton();
        admin = new javax.swing.JLabel();
        users = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        safal = new javax.swing.JLabel();
        student = new javax.swing.JLabel();
        sbsidebar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dashyybo = new javax.swing.JLabel();
<<<<<<< HEAD
        sb = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
=======
        notification = new javax.swing.JLabel();
        sb = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
        jPanel3 = new javax.swing.JPanel();
        booksborrowe = new javax.swing.JLabel();
        three = new javax.swing.JLabel();
        twoduethisweek = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Reservation = new javax.swing.JLabel();
        two = new javax.swing.JLabel();
        onereadyforpickup = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        rsfourtyfive = new javax.swing.JLabel();
        oneoverduebook = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        booksread = new javax.swing.JLabel();
        twentyfour = new javax.swing.JLabel();
        thissemester = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        currentlyborrowed = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cleancode = new javax.swing.JLabel();
        robertcmartin = new javax.swing.JLabel();
        duemaytwentyfive = new javax.swing.JLabel();
<<<<<<< HEAD
        renew = new javax.swing.JButton();
=======
        RenewButton = new javax.swing.JButton();
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
        jButton13 = new javax.swing.JButton();
        duesoon = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
<<<<<<< HEAD
        secondrenew = new javax.swing.JButton();
=======
        RenewButton2 = new javax.swing.JButton();
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
        secondreturn = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
<<<<<<< HEAD
        thirdreturn = new javax.swing.JButton();
=======
        ReturnButton = new javax.swing.JButton();
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
        payfine = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        recommendedforu = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
<<<<<<< HEAD
        jButton19 = new javax.swing.JButton();
=======
        ReserveButton = new javax.swing.JButton();
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
        jPanel14 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
<<<<<<< HEAD
        jButton20 = new javax.swing.JButton();
=======
        BorrowButton = new javax.swing.JButton();
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
        jPanel15 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
<<<<<<< HEAD
        jButton21 = new javax.swing.JButton();
=======
        JoinWaitlistButton = new javax.swing.JButton();
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
        seemore = new javax.swing.JLabel();
        viewall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 58, 107));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        libraryMs.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        libraryMs.setForeground(new java.awt.Color(255, 255, 255));
        libraryMs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/library_1-removebg-preview (2).png"))); // NOI18N
        libraryMs.setText("LibraryMs");

        dashboard.setBackground(new java.awt.Color(27, 58, 107));
        dashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colourful_house-removebg-preview (1).png"))); // NOI18N
        dashboard.setText(" Dashboard");

        member.setForeground(new java.awt.Color(255, 255, 255));
        member.setText("MEMBER");

        booksearch.setBackground(new java.awt.Color(27, 58, 107));
        booksearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        booksearch.setForeground(new java.awt.Color(255, 255, 255));
        booksearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colourful_search-removebg-previe.png"))); // NOI18N
        booksearch.setText(" Book Search");

        myborrowings.setBackground(new java.awt.Color(27, 58, 107));
        myborrowings.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        myborrowings.setForeground(new java.awt.Color(255, 255, 255));
        myborrowings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colourful_borrowing-removebg-pre.png"))); // NOI18N
        myborrowings.setText(" My Borrowings");

        wishlist.setBackground(new java.awt.Color(27, 58, 107));
        wishlist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        wishlist.setForeground(new java.awt.Color(255, 255, 255));
        wishlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colourful_wishlist-removebg-prev.png"))); // NOI18N
        wishlist.setText(" Wishlist");

        reviews.setBackground(new java.awt.Color(27, 58, 107));
        reviews.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reviews.setForeground(new java.awt.Color(255, 255, 255));
        reviews.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colourful_reviews-removebg-previ.png"))); // NOI18N
        reviews.setText(" Reviews");

        finepayment.setBackground(new java.awt.Color(27, 58, 107));
        finepayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        finepayment.setForeground(new java.awt.Color(255, 255, 255));
        finepayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colourful_fine-removebg-preview (1).png"))); // NOI18N
        finepayment.setText(" Fine Payment");

        myaccount.setBackground(new java.awt.Color(27, 58, 107));
        myaccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        myaccount.setForeground(new java.awt.Color(255, 255, 255));
        myaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colorful_my_account-removebg-pre.png"))); // NOI18N
        myaccount.setText(" My Account");

        inventory.setBackground(new java.awt.Color(27, 58, 107));
        inventory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventory.setForeground(new java.awt.Color(255, 255, 255));
        inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colourful_inv_98-removebg-previe.png"))); // NOI18N
        inventory.setText("Inventory");

        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("ADMIN");

        users.setBackground(new java.awt.Color(27, 58, 107));
        users.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        users.setForeground(new java.awt.Color(255, 255, 255));
        users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colourful_users-removebg-preview (1).png"))); // NOI18N
        users.setText(" users");

        reports.setBackground(new java.awt.Color(27, 58, 107));
        reports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reports.setForeground(new java.awt.Color(255, 255, 255));
        reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colourful_reports-removebg-previ.png"))); // NOI18N
        reports.setText("Reports");

        safal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        safal.setForeground(new java.awt.Color(255, 255, 255));
        safal.setText("Safal Bhandari");

        student.setForeground(new java.awt.Color(255, 255, 255));
        student.setText("Student Member");

        sbsidebar.setBackground(new java.awt.Color(0, 255, 102));
        sbsidebar.setText("SB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(reports)
                        .addComponent(users)
                        .addComponent(libraryMs)
                        .addComponent(myborrowings)
                        .addComponent(dashboard)
                        .addComponent(booksearch)
                        .addComponent(wishlist)
                        .addComponent(finepayment)
                        .addComponent(reviews)
                        .addComponent(member)
                        .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inventory)
                        .addComponent(myaccount))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sbsidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(safal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(student)
                                .addGap(10, 10, 10)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(libraryMs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(member)
                .addGap(24, 24, 24)
                .addComponent(dashboard)
                .addGap(26, 26, 26)
                .addComponent(booksearch)
                .addGap(26, 26, 26)
                .addComponent(myborrowings)
                .addGap(24, 24, 24)
                .addComponent(wishlist)
                .addGap(26, 26, 26)
                .addComponent(reviews)
                .addGap(29, 29, 29)
                .addComponent(finepayment)
                .addGap(27, 27, 27)
                .addComponent(myaccount)
                .addGap(28, 28, 28)
                .addComponent(admin)
                .addGap(18, 18, 18)
                .addComponent(inventory)
                .addGap(27, 27, 27)
                .addComponent(users)
                .addGap(27, 27, 27)
                .addComponent(reports)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(safal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(student))
                    .addComponent(sbsidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        dashyybo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        dashyybo.setText("Dashboard");

<<<<<<< HEAD
=======
        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rangg (1).png"))); // NOI18N
        notification.setText("jLabel3");

>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
        sb.setBackground(new java.awt.Color(0, 255, 0));
        sb.setText("SB");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("Search books , authors , ISBN");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yoyo-removebg-preview (1).png"))); // NOI18N
        jLabel4.setText("jLabel4");

<<<<<<< HEAD
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rangg (1).png"))); // NOI18N

=======
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(dashyybo)
                .addGap(326, 326, 326)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
<<<<<<< HEAD
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
=======
                .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sb, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(sb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
=======
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dashyybo)
<<<<<<< HEAD
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
=======
                                .addComponent(notification)
                                .addComponent(jLabel4)))
                        .addGap(0, 3, Short.MAX_VALUE)))
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        booksborrowe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        booksborrowe.setText("Books Borrowed");

        three.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        three.setText("3");

        twoduethisweek.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        twoduethisweek.setText("2 due this week");

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colourful_borrowing-removebg-pre (1).png"))); // NOI18N
        jLabel39.setText("jLabel39");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(booksborrowe)
                .addGap(60, 60, 60))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(twoduethisweek, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(booksborrowe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(three)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoduethisweek)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        Reservation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Reservation.setText("Reservations");

        two.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        two.setText("2");

        onereadyforpickup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        onereadyforpickup.setText("1 ready for pickup");

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reserve-removebg-preview (2).png"))); // NOI18N
        jLabel38.setText("jLabel38");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onereadyforpickup)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reservation))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Reservation)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel38)
                        .addComponent(two))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(onereadyforpickup)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Outsatnding Fines");

        rsfourtyfive.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rsfourtyfive.setText("Rs 45");

        oneoverduebook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        oneoverduebook.setText("1 overdue book");

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paymnet98-removebg-preview (1).png"))); // NOI18N
        jLabel35.setText("jLabel35");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oneoverduebook)
                    .addComponent(rsfourtyfive)
                    .addComponent(jLabel8))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(rsfourtyfive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oneoverduebook)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        booksread.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        booksread.setText("Books Read");

        twentyfour.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        twentyfour.setText("24");

        thissemester.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        thissemester.setText("This semester");

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greentick-removebg-preview (1).png"))); // NOI18N
        jLabel40.setText("jLabel40");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thissemester)
                    .addComponent(twentyfour, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booksread, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(booksread)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twentyfour)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thissemester)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        currentlyborrowed.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        currentlyborrowed.setText("Currently Borrowed");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        cleancode.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        cleancode.setText("Clean Code");

        robertcmartin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        robertcmartin.setText("Robert C Martin");

        duemaytwentyfive.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        duemaytwentyfive.setText("Due : may 25, 2026");

<<<<<<< HEAD
        renew.setBackground(new java.awt.Color(238, 242, 247));
        renew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        renew.setText("Renew");
=======
        RenewButton.setBackground(new java.awt.Color(238, 242, 247));
        RenewButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RenewButton.setText("Renew");
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee

        jButton13.setBackground(new java.awt.Color(238, 242, 247));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton13.setText("Return");

        duesoon.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        duesoon.setText("Due Soon");

        jPanel10.setBackground(new java.awt.Color(27, 58, 107));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books2-removebg-preview (2).png"))); // NOI18N
        jLabel33.setText("jLabel33");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
<<<<<<< HEAD
                        .addComponent(renew)
=======
                        .addComponent(RenewButton)
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                        .addGap(18, 18, 18)
                        .addComponent(jButton13))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(robertcmartin, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cleancode, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duesoon)
                            .addComponent(duemaytwentyfive))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(cleancode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(robertcmartin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duemaytwentyfive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duesoon))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
<<<<<<< HEAD
                    .addComponent(renew))
=======
                    .addComponent(RenewButton))
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel24.setText("The Great Gatsby");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("F.Scott Figerland");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Due : May 12, 2026");

<<<<<<< HEAD
        secondrenew.setBackground(new java.awt.Color(238, 242, 247));
        secondrenew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        secondrenew.setText("Renew");
=======
        RenewButton2.setBackground(new java.awt.Color(238, 242, 247));
        RenewButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RenewButton2.setText("Renew");
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee

        secondreturn.setBackground(new java.awt.Color(238, 242, 247));
        secondreturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        secondreturn.setText("Return");

        jLabel31.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("On Time");

        jPanel11.setBackground(new java.awt.Color(30, 136, 73));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colourful_books_98-removebg-prev.png"))); // NOI18N
        jLabel34.setText("jLabel34");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel34)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
<<<<<<< HEAD
                        .addComponent(secondrenew)
=======
                        .addComponent(RenewButton2)
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                        .addGap(18, 18, 18)
                        .addComponent(secondreturn))
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26)
                    .addComponent(jLabel31))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondreturn)
<<<<<<< HEAD
                    .addComponent(secondrenew))
=======
                    .addComponent(RenewButton2))
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel27.setText("Design Patterns");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Gang of Four");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Due : April 28 2026   Fine : Rs 45");

<<<<<<< HEAD
        thirdreturn.setBackground(new java.awt.Color(238, 242, 247));
        thirdreturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        thirdreturn.setText("Return");
=======
        ReturnButton.setBackground(new java.awt.Color(238, 242, 247));
        ReturnButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReturnButton.setText("Return");
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee

        payfine.setBackground(new java.awt.Color(238, 242, 247));
        payfine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payfine.setText("Pay Fine");

        jLabel32.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel32.setText("Overdue");

        jPanel12.setBackground(new java.awt.Color(123, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/orangebook-removebg-preview (1) (2).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29)
                            .addComponent(jLabel32)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
<<<<<<< HEAD
                        .addComponent(thirdreturn)
=======
                        .addComponent(ReturnButton)
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                        .addGap(18, 18, 18)
                        .addComponent(payfine)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32))
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
<<<<<<< HEAD
                    .addComponent(thirdreturn)
=======
                    .addComponent(ReturnButton)
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                    .addComponent(payfine))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        recommendedforu.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        recommendedforu.setText("Recommended for You");

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jPanel16.setBackground(new java.awt.Color(185, 119, 14));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/orangebook98-removebg-preview (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel43.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel43.setText("Atomic Habits");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel44.setText("James Clear");

        jLabel45.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel45.setText("Self -Help");

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stars-removebg-preview (1).png"))); // NOI18N
        jLabel46.setText("jLabel46");

<<<<<<< HEAD
        jButton19.setBackground(new java.awt.Color(27, 58, 107));
        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Reserve");
=======
        ReserveButton.setBackground(new java.awt.Color(27, 58, 107));
        ReserveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReserveButton.setForeground(new java.awt.Color(255, 255, 255));
        ReserveButton.setText("Reserve");
        ReserveButton.addActionListener(this::ReserveButtonActionPerformed);
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
<<<<<<< HEAD
                        .addComponent(jButton19)))
=======
                        .addComponent(ReserveButton)))
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel44)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel45))
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
<<<<<<< HEAD
                .addComponent(jButton19)
=======
                .addComponent(ReserveButton)
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jPanel17.setBackground(new java.awt.Color(27, 59, 107));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bluebook98 (1) (1).png"))); // NOI18N
        jLabel58.setText("jLabel58");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel58)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel47.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel47.setText("The programatic Programmer");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel48.setText("Andrew Hunt");

        jLabel49.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel49.setText("Technology");

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stars-removebg-preview (1).png"))); // NOI18N
        jLabel50.setText("jLabel50");

<<<<<<< HEAD
        jButton20.setBackground(new java.awt.Color(27, 58, 107));
        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("Borrow");
=======
        BorrowButton.setBackground(new java.awt.Color(27, 58, 107));
        BorrowButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BorrowButton.setForeground(new java.awt.Color(255, 255, 255));
        BorrowButton.setText("Borrow");
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel47)))
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
<<<<<<< HEAD
                        .addComponent(jButton20)))
=======
                        .addComponent(BorrowButton)))
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
<<<<<<< HEAD
                .addComponent(jButton20)
=======
                .addComponent(BorrowButton)
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jPanel18.setBackground(new java.awt.Color(74, 35, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/purplebook-removebg-preview (1) (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(21, 21, 21))
        );

        jLabel51.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel51.setText("Dune");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel52.setText("Frank Herbert");

        jLabel53.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel53.setText("Sci-Fi");

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stars-removebg-preview (1).png"))); // NOI18N
        jLabel54.setText("jLabel54");

<<<<<<< HEAD
        jButton21.setBackground(new java.awt.Color(27, 58, 107));
        jButton21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Join Waitlist");
=======
        JoinWaitlistButton.setBackground(new java.awt.Color(27, 58, 107));
        JoinWaitlistButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JoinWaitlistButton.setForeground(new java.awt.Color(255, 255, 255));
        JoinWaitlistButton.setText("Join Waitlist");
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel52)
                                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
<<<<<<< HEAD
                        .addComponent(jButton21)))
=======
                        .addComponent(JoinWaitlistButton)))
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
<<<<<<< HEAD
                .addComponent(jButton21)
=======
                .addComponent(JoinWaitlistButton)
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        seemore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seemore.setForeground(new java.awt.Color(30, 132, 73));
        seemore.setText("See more ");

        viewall.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewall.setForeground(new java.awt.Color(30, 132, 73));
        viewall.setText("View all");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(recommendedforu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(seemore))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(currentlyborrowed)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1015, Short.MAX_VALUE)
                                        .addComponent(viewall, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)))
                        .addGap(47, 47, 47))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentlyborrowed)
                    .addComponent(viewall))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recommendedforu)
                    .addComponent(seemore))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
=======
    private void ReserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveButtonActionPerformed
        String bookTitle = jLabel43.getText();
        String author = jLabel44.getText();

        if (reservationService.isAlreadyReserved(bookTitle, CURRENT_MEMBER_NAME)) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "You already have a reservation for \"" + bookTitle + "\".",
                    "Already Reserved",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int choice = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Reserve \"" + bookTitle + "\" by " + author + "?",
                "Confirm Reservation",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (choice != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        Reservation reservation = reservationService.reserve(bookTitle, author, CURRENT_MEMBER_NAME);
        logger.info("Reservation created: " + reservation);

        ReserveButton.setText("Reserved");
        ReserveButton.setEnabled(false);

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "\"" + bookTitle + "\" has been reserved. We'll notify you when it's ready for pickup.",
                "Reservation Confirmed",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ReserveButtonActionPerformed

>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ui().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JLabel Reservation;
=======
    private javax.swing.JButton BorrowButton;
    private javax.swing.JButton JoinWaitlistButton;
    private javax.swing.JButton RenewButton;
    private javax.swing.JButton RenewButton2;
    private javax.swing.JLabel Reservation;
    private javax.swing.JButton ReserveButton;
    private javax.swing.JButton ReturnButton;
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
    private javax.swing.JLabel admin;
    private javax.swing.JLabel booksborrowe;
    private javax.swing.JButton booksearch;
    private javax.swing.JLabel booksread;
    private javax.swing.JLabel cleancode;
    private javax.swing.JLabel currentlyborrowed;
    private javax.swing.JButton dashboard;
    private javax.swing.JLabel dashyybo;
    private javax.swing.JLabel duemaytwentyfive;
    private javax.swing.JLabel duesoon;
    private javax.swing.JButton finepayment;
    private javax.swing.JButton inventory;
    private javax.swing.JButton jButton13;
<<<<<<< HEAD
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
=======
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel libraryMs;
    private javax.swing.JLabel member;
    private javax.swing.JButton myaccount;
    private javax.swing.JButton myborrowings;
<<<<<<< HEAD
=======
    private javax.swing.JLabel notification;
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
    private javax.swing.JLabel oneoverduebook;
    private javax.swing.JLabel onereadyforpickup;
    private javax.swing.JButton payfine;
    private javax.swing.JLabel recommendedforu;
<<<<<<< HEAD
    private javax.swing.JButton renew;
=======
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
    private javax.swing.JButton reports;
    private javax.swing.JButton reviews;
    private javax.swing.JLabel robertcmartin;
    private javax.swing.JLabel rsfourtyfive;
    private javax.swing.JLabel safal;
    private javax.swing.JButton sb;
    private javax.swing.JButton sbsidebar;
<<<<<<< HEAD
    private javax.swing.JButton secondrenew;
    private javax.swing.JButton secondreturn;
    private javax.swing.JLabel seemore;
    private javax.swing.JLabel student;
    private javax.swing.JButton thirdreturn;
=======
    private javax.swing.JButton secondreturn;
    private javax.swing.JLabel seemore;
    private javax.swing.JLabel student;
>>>>>>> a5cde2a5e3d1b6888ea5e29bf3922b1529638eee
    private javax.swing.JLabel thissemester;
    private javax.swing.JLabel three;
    private javax.swing.JLabel twentyfour;
    private javax.swing.JLabel two;
    private javax.swing.JLabel twoduethisweek;
    private javax.swing.JButton users;
    private javax.swing.JLabel viewall;
    private javax.swing.JButton wishlist;
    // End of variables declaration//GEN-END:variables
}
